Cargo.toml, src/lib.rs
See novifinancial/opaque-ke#187.
=> Re-export `simd_backend`

src/group/p256.rs
Reduce some allocations.
Improves `to_bytes()`. It's not necessary to call `mod_floor` because all calculations are done with it anyway. I noticed that we could also save an unnecessary call in `pow_internal`.
See novifinancial/opaque-ke#244.
=> P256 improvements

.cargo/license.rs, .github/workflows/main.yml, Cargo.toml, rustfmt.toml, src/group/expand.rs, src/group/mod.rs, src/group/p256.rs, src/group/ristretto.rs, src/group/tests.rs, src/lib.rs, src/serialization.rs, src/tests/mock_rng.rs, src/tests/voprf_test_vectors.rs, src/util.rs, src/voprf.rs, taplo.toml
Rustfmt by default does the right thing, though there are some improvements that can be made by using unstable features. This does require nightly, but adds a couple of nice features that don't have to be done manually anymore:
- Check the license header.
- Format comments.
- Format code in doc comments
- Properly sort and enforce import granularity.
I can also add [Taplo](https://crates.io/crates/taplo) to format TOML files if you would like, no real effort required.
Based on #34 so I don't have to re-base.
=> Configure Rustfmt and Taplo

.github/workflows/main.yml, Cargo.toml, src/error.rs, src/group/expand.rs, src/group/mod.rs, src/group/p256.rs, src/group/ristretto.rs, src/group/tests.rs, src/lib.rs, src/serialization.rs, src/tests/voprf_test_vectors.rs, src/util.rs, src/voprf.rs
- Add a `Result` shorthand: `Result<T, InternalError`.
- Rename `InternalError` to `Error`, I believe this was an artifact when we still had multiple error types.
- Re-export `Group`, `Result`, `Error`, `VerifiableClientBatchFinalizeResult` and `VerifiableServerBatchEvaluateResult`.
- Made `group` and `error` modules private, because of re-exports.
- Re-export `Proof`, this was kinda a bug because downstream users couldn't use that type, strange that Rust didn't complain.
- Move `deserialize` to the `serialize` module, the only place it was used.
- Make `serialize` and `serialize_owned` to methods of `Serialized`, which was renamed to `Serialize`.
- Update p256 to 0.10.
=> General Improvements

Cargo.toml
Just recently learned this is possible. I don't believe there is a difference, but it seems to be more common and whats "recommended": https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field.
=> Reduce version requirement

src/lib.rs, src/tests/mod.rs, src/tests/voprf_test_vectors.rs, src/voprf.rs
This addresses the last function not available without `alloc`. This was discussed in #42.
Builds on #47.
=> `batch_evaluate` without `alloc`

Cargo.toml, src/error.rs, src/group/expand.rs, src/group/mod.rs, src/group/p256.rs, src/group/ristretto.rs, src/group/tests.rs, src/lib.rs, src/serialization.rs, src/tests/voprf_test_vectors.rs, src/tests/voprf_vectors.rs, src/util.rs, src/voprf.rs
Replaces #49.
- Move `Group` constraints to associated type: `Elem`.
- Implement `Group` for `NistP256` instead of `ProjectivePoint`.
- Implement `Group` for `Ristretto255`, our own type, instead of `RistrettoPoint`. This type is re-exported.
- Change `SUITE_ID` to `u16`.
- Reworked scalar de-serialization, now scalars are actually checked for validity and not reduced or clamped into validity. Zero-checking is now not a separate function.
- Reworked `hash_to_scalar` and `hash_to_curve` not take iterators anymore in preparation of RustCrypto/traits#876. This included reverting a lot of convenience utilities. Maybe we will come up with alternatives in the future.
- Reworked `expand_message_xmd` in with some additional constraints according to the spec.
- Simplify P-256 `HashToScalar` …
=> `Group` trait overhaul

src/error.rs, src/group/elliptic_curve.rs, src/group/mod.rs, src/group/ristretto.rs, src/group/tests.rs, src/lib.rs, src/serialization.rs, src/util.rs, src/voprf.rs
Basically add `clippy::missing_errors_doc`. Re-introduced `InternalError` to return something from `hash_to_curve` and `hash_to_scalar` that is actually not an error returned by the public API.
=> Document all `Error`s

Cargo.toml, src/lib.rs, src/voprf.rs
Builds on top of #56.
~~Still waits for a new release of `derive-where`.~~
Moving to `ZeroizeOnDrop` gives us what we want without allowing the user to break all invariants we provide.
=> Move to `ZeroizeOnDrop`

Cargo.toml, src/error.rs, src/group/elliptic_curve.rs, src/group/mod.rs, src/group/ristretto.rs, src/lib.rs, src/oprf.rs, src/poprf.rs, src/serialization.rs, src/tests/test_cfrg_vectors.rs, src/util.rs, src/voprf.rs
This builds on top of #58.
- Remove `hex` from dependencies.
- Revert `std` as `default` feature.
- Correct error documentation.
- Revert old change of passing `Mode` into `hash_to_curve` and `hash_to_scalar`.
- Fix documentation tests.
- Fix documentation links.
- Introduce no alloc version of `batch_evaluate` for POPRF and VOPRF.
- Fix wrong errors.
- Fix returning `Result` instead of panicking when using `derive_key_pair`.
- Change public functions to take iterators instead of slices when batching.
- Remove some unnecessarily returned `Result`s.
- Improve `derive_keypair`.
- Remove `i2osp_1`.
- Some general code improvements.
Sadly I was unable to make a complete no alloc solution for POPRF despite my hopes mentioned on Slack.
I apologize for this single mega-commit!
=> #58 review

Cargo.toml
While working on novifinancial/opaque-ke#261 I realized that the current version of `x25519-dalek` is not compatible with RustCrypto because it pins for example `zeroize` to an old version. Cargo doesn't not allow the same major version of a dependency to exist in the same dependency tree.
After some research I pretty much established that the pre-releases are not really experimental but are just semver-incompatible versions of the stable versions with updated dependencies. Basically it fits our bill.
In `opaque-ke` we will pull the pre-release versions of `curve25519-dalek` and `x25519-dalek` and won't have tons of duplicate dependencies this way.
=> Update to `curve25519-dalek` pre-release

CHANGELOG.md, Cargo.toml, README.md, src/common.rs, src/lib.rs, src/oprf.rs, src/poprf.rs, src/tests/test_cfrg_vectors.rs, src/voprf.rs
This PR updates the implementation to draft-11: 
- The main change is that it introduces `evaluate()` on the server-side and renames the existing `evaluate()` to `blind_evaluate()` to match the spec.
- Adds unit tests and completes the vector tests
- Adds documentation with sample code
Miscellaneous change: The PR inverts the order of arguments for `PoprfClient::blind()` to align it with the other clients.
@kevinlewi I'm not sure the renaming/documentation is to your liking, happy to make changes.
=> Updating to draft 11

.github/workflows/main.yml, Cargo.toml, src/group/ristretto.rs, src/lib.rs
There has now been some significant positive movement on `curve25519`, including updated dependencies.
I also added the `doc_auto_cfg` feature behind a `docsrs` `cfg` flag to improve the documentation generated.
I guess for us the biggest change is removing all the re-exported crate features. Now `--all-features` can be used and features are additive, as they should be.
CI might need to be improved now, like testing `--all-features` or 32-bit targets. @kevinlewi I gave you write access, so feel free to add more tests as you deem fit.
=> Update `curve25519-dalek` to 4.0.0-pre.5

CHANGELOG.md, Cargo.toml, README.md
=> Publishing 0.5.0-pre.1

Cargo.toml, src/tests/test_cfrg_vectors.rs
`json` was flagged by `cargo-audit` as unmaintained, which is my impression too.
=> Replace `json` with `serde_json`

.github/workflows/main.yml, src/common.rs, src/tests/parser.rs
Addresses the latest added warn-by-default lints in Clippy.
Also noticed that CI didn't test all crate features with Clippy.
=> Fix Clippy

src/group/elliptic_curve.rs
This reverts the unfortunate changes that had to be made in #91.
It was fixed in https://github.com/RustCrypto/elliptic-curves/pull/722.
This will actually require downstream users to update their `primeorder` dependency to v0.12.1, personally I don't think it is a problem, but the gain is also very minor.
=> Depend on `ProjectivePoint: ToEncodedPoint`

Cargo.toml, src/common.rs, src/lib.rs, src/oprf.rs, src/poprf.rs, src/voprf.rs
Since we are now using Rust 1.60, we can use explicit crate features.
Rust-Analyzer had some serious issues with that `extern crate serde_ as serde`.
This also removes all implicit features, which is an improvement for users.
=> Use explicit crate features

Cargo.toml, src/group/tests.rs, src/oprf.rs, src/poprf.rs, src/serialization.rs, src/tests/test_cfrg_vectors.rs, src/voprf.rs
This just tests P-384 support and builds on top of https://github.com/RustCrypto/elliptic-curves/pull/600.
We still have to wait for new versions to be released.
Builds on top of https://github.com/facebook/voprf/pull/101.
Fixes #81.
=> Test P-384

.github/workflows/main.yml, Cargo.toml, README.md
:rocket: :tada:
I think we should make a another pre-release and do a proper release after https://github.com/dalek-cryptography/curve25519-dalek/issues/405.
Replaces #105.
=> Update RustCrypto dependencies to v0.13

Cargo.toml
Nothing significant changed for `voprf`.
=> Bump `curve25519-dalek` to v4.0.0-rc.3

Cargo.toml
Dependabot seems to be on vacation.
=> Bump `curve25519-dalek` to v4

Cargo.toml, src/group/tests.rs, src/oprf.rs, src/poprf.rs, src/serialization.rs, src/tests/test_cfrg_vectors.rs, src/voprf.rs
This adds testing of P-521 through the [`p521`](https://crates.io/crates/p521) crate.
Still requires:
See #84 for a previously similar addition.
See https://github.com/facebook/opaque-ke/pull/349 for the same PR in `opaque-ke`, which doesn't rely on this PR.
=> Test P-521

.github/workflows/main.yml, Cargo.toml, src/common.rs, src/error.rs, src/group/elliptic_curve.rs, src/group/mod.rs, src/oprf.rs, src/poprf.rs, src/serialization.rs, src/tests/test_cfrg_vectors.rs, src/voprf.rs
- Update MSRV to v1.83. Now a lot of our trait constraints aren't viral anymore, but are implied! This gets rid of all the `where` constraints on structs and implementations!
- With the new MSRV, we can now implement `Error` for our error types without `std` as well.
- Move de/serialization constraints on implementations directly onto `Group`, now that the constraints aren't viral anymore.
This is a huge improvement to the documentation as well, which was littered with these huge `where`-clauses.
=> Bump MSRV to v1.83

Cargo.toml
Currently users would have to depend manually on `curve25519-dalek` to enable Serde.
This seems to have been lost back in https://github.com/facebook/voprf/pull/28, I suspect because enabling crate features on optional dependencies with `?` wasn't available back then.
Analogous to https://github.com/facebook/opaque-ke/pull/375.
=> Enable `curve25519-dalek/serde`

src/group/ristretto.rs
The [specification states](https://www.rfc-editor.org/rfc/rfc9497#name-rejection-sampling):
> Generate a random byte array with Ns bytes and attempt to map to a Scalar by calling `DeserializeScalar` in constant time. If it succeeds, return the result. If it fails, try again with another random byte array until the procedure succeeds.
While the `elliptic-curve` implementation did just that, the `curve25519-dalek` did not, instead it simply reduced to a correct scalar. The specification proposes an [alternative to rejection sampling](https://www.rfc-editor.org/rfc/rfc9497#name-random-number-generation-us), however for Ristretto255 it requires reducing from 48 bytes, the `curve25519-dalek` implementation was reducing from 64 bytes.
With the help of `FromOkm` we might want to consider …
=> Align `Ristretto255::random_scalar()` with specification
